config/routes.rb
Travel::Application.routes.draw do
  get '/photo_responses/new', controller: 'photo_responses', action: 'new', as: 'new_photo_response'
  post '/photo_responses', controller: 'photo_responses', action: 'create', as: 'photo_responses'

  get '/photo_responses', controller: 'photo_responses', action: 'index'
  get '/photo_responses/:id', controller: 'photo_responses', action: 'show', as: 'photo_response'

  get '/photo_responses/:id/edit', controller: 'photo_responses', action: 'edit', as: 'edit_photo_response'
  patch '/photo_responses/:id', controller: 'photo_responses', action: 'update'

  delete '/photo_responses/:id', controller: 'photo_responses', action: 'destroy'

  root 'requests#index'

  get '/photos/new', controller: 'photos', action: 'new', as: 'new_photo'
  post '/photos', controller: 'photos', action: 'create', as: 'photos'

  get '/photos', controller: 'photos', action: 'index'
  get '/photos/:id', controller: 'photos', action: 'show', as: 'photo'

  get '/photos/:id/edit', controller: 'photos', action: 'edit', as: 'edit_photo'
  patch '/photos/:id', controller: 'photos', action: 'update'

  delete '/photos/:id', controller: 'photos', action: 'destroy'

  get '/replies/new', controller: 'replies', action: 'new', as: 'new_reply'
  post '/replies', controller: 'replies', action: 'create', as: 'replies'

  get '/replies', controller: 'replies', action: 'index'
  get '/replies/:id', controller: 'replies', action: 'show', as: 'reply'

  get '/replies/:id/edit', controller: 'replies', action: 'edit', as: 'edit_reply'
  patch '/replies/:id', controller: 'replies', action: 'update'

  delete '/replies/:id', controller: 'replies', action: 'destroy'

  get '/requests/new', controller: 'requests', action: 'new', as: 'new_request'
  post '/requests', controller: 'requests', action: 'create', as: 'requests'

  get '/requests', controller: 'requests', action: 'index'
  get '/requests/:id', controller: 'requests', action: 'show', as: 'request'

  get '/requests/:id/edit', controller: 'requests', action: 'edit', as: 'edit_request'
  patch '/requests/:id', controller: 'requests', action: 'update'

  delete '/requests/:id', controller: 'requests', action: 'destroy'

  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create', as: 'users'

  get '/users', controller: 'users', action: 'index'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  patch '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

end

app/models/reply.rb
class Reply < ActiveRecord::Base

has_many :photos

belongs_to :user

belongs_to :request


end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController

  def index
    @replies = Reply.all
  end

  def show
    @reply = Reply.find_by(id: params[:id])
  end

  def new
  end

  def create
    @reply = Reply.new
    @reply.user_id = params[:user_id]
    @reply.request_id = params[:request_id]
    @reply.reply_text = params[:reply_text]
    @reply.expert_star_rating = params[:expert_star_rating]
    @reply.expert_review = params[:expert_review]
    @reply.traveler_star_rating = params[:traveler_star_rating]

    if @reply.save
      redirect_to replies_url, notice: "Reply created successfully."
    else
      render 'new'
    end
  end

  def edit
    @reply = Reply.find_by(id: params[:id])
  end

  def update
    @reply = Reply.find_by(id: params[:id])
    @reply.user_id = params[:user_id]
    @reply.request_id = params[:request_id]
    @reply.reply_text = params[:reply_text]
    @reply.expert_star_rating = params[:expert_star_rating]
    @reply.expert_review = params[:expert_review]
    @reply.traveler_star_rating = params[:traveler_star_rating]

    if @reply.save
      redirect_to replies_url, notice: "Reply updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @reply = Reply.find_by(id: params[:id])
    @reply.destroy

    redirect_to replies_url, notice: "Reply deleted."
  end
end

app/views/replies/edit.html.erb
<div class="page-header">
  <h1>Editing Your Reply </h1>
</div>

<%= form_tag(reply_url(@reply), method: 'patch', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :user_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
       <%= select_tag :user_id, options_from_collection_for_select(User.all, :id, :full_name, @reply.user_id), class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :request_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
    <%= select_tag :request_id, options_from_collection_for_select(Request.all, :id, :travel_to_city, @reply.request_id),class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :reply_text, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_area_tag :reply_text, @reply.reply_text, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Update Reply", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/replies/index.html.erb
<div class="page-header">
  <h1>Replies</h1>
</div>

<p><%= link_to 'Add a New Reply', new_reply_url, class: 'btn btn-primary' %></p>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Expert</th>
      <th>Trip Title</th>
      <th>Reply text</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @replies.each do |reply| %>
      <tr>
        <td><%= reply.user.full_name %></td>
        <td><%= reply.request.travel_to_city %></td>
        <td><%= reply.reply_text %></td>
        <td><%= link_to '<i class="fa fa-search-plus"></i>'.html_safe, reply_url(reply), class: 'btn btn-primary' %></td>
        <td><%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_reply_url(reply), class: 'btn btn-warning' %></td>
        <td><%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, reply_url(reply), method: 'delete', data: { confirm: "Do you really want to delete this reply?" }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/replies/new.html.erb
<div class="page-header">
  <h1>New Reply</h1>
</div>

<%= form_tag(replies_url, method: 'post', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :user_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
       <%= select_tag :user_id, options_from_collection_for_select(User.all, :id, :full_name), class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :request_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= select_tag :request_id, options_from_collection_for_select(Request.all, :id, :travel_to_city),class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :reply_text, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_area_tag :reply_text, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Create Reply", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/replies/show.html.erb
<div class="page-header">
  <h3><%= @reply.user.full_name %>'s Reply to <%= @reply.request.user.full_name %>'s Travel Request</h3>
</div>

<dl class="dl-horizontal">
  <dt>Expert</dt>
  <dd><%= @reply.user.full_name %></dd>

  <dt>Traveller</dt>
  <dd><%= @reply.request.user.full_name %></dd>

  <dt>Trip</dt>
  <dd><%= @reply.request.travel_to_city %></dd>

  <dt>Request text</dt>
  <dd><%= @reply.request.request_text %></dd>

  <dt>Reply text</dt>
  <dd><%= @reply.reply_text %></dd>

  
</dl>