config/routes.rb
Travel::Application.routes.draw do
  get '/photo_responses/new', controller: 'photo_responses', action: 'new', as: 'new_photo_response'
  post '/photo_responses', controller: 'photo_responses', action: 'create', as: 'photo_responses'

  get '/photo_responses', controller: 'photo_responses', action: 'index'
  get '/photo_responses/:id', controller: 'photo_responses', action: 'show', as: 'photo_response'

  get '/photo_responses/:id/edit', controller: 'photo_responses', action: 'edit', as: 'edit_photo_response'
  patch '/photo_responses/:id', controller: 'photo_responses', action: 'update'

  delete '/photo_responses/:id', controller: 'photo_responses', action: 'destroy'

  root 'requests#index'

  get '/photos/new', controller: 'photos', action: 'new', as: 'new_photo'
  post '/photos', controller: 'photos', action: 'create', as: 'photos'

  get '/photos', controller: 'photos', action: 'index'
  get '/photos/:id', controller: 'photos', action: 'show', as: 'photo'

  get '/photos/:id/edit', controller: 'photos', action: 'edit', as: 'edit_photo'
  patch '/photos/:id', controller: 'photos', action: 'update'

  delete '/photos/:id', controller: 'photos', action: 'destroy'

  get '/replies/new', controller: 'replies', action: 'new', as: 'new_reply'
  post '/replies', controller: 'replies', action: 'create', as: 'replies'

  get '/replies', controller: 'replies', action: 'index'
  get '/replies/:id', controller: 'replies', action: 'show', as: 'reply'

  get '/replies/:id/edit', controller: 'replies', action: 'edit', as: 'edit_reply'
  patch '/replies/:id', controller: 'replies', action: 'update'

  delete '/replies/:id', controller: 'replies', action: 'destroy'

  get '/requests/new', controller: 'requests', action: 'new', as: 'new_request'
  post '/requests', controller: 'requests', action: 'create', as: 'requests'

  get '/requests', controller: 'requests', action: 'index'
  get '/requests/:id', controller: 'requests', action: 'show', as: 'request'

  get '/requests/:id/edit', controller: 'requests', action: 'edit', as: 'edit_request'
  patch '/requests/:id', controller: 'requests', action: 'update'

  delete '/requests/:id', controller: 'requests', action: 'destroy'

  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create', as: 'users'

  get '/users', controller: 'users', action: 'index'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  patch '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

end

app/models/user.rb
class User < ActiveRecord::Base

has_many :requests

def full_name                                                                                                                                                                                     
  ([first_name, last_name] - ['']).compact.join(' ')                         
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  def new
  end

  def create
    @user = User.new
    @user.first_name = params[:first_name]
    @user.last_name = params[:last_name]
    @user.home_city = params[:home_city]
    @user.home_state = params[:home_state]
    @user.home_country = params[:home_country]
    @user.email = params[:email]
    @user.user_name = params[:user_name]
    @user.password = params[:password]
    @user.photo_url = params[:photo_url]

    if @user.save
      redirect_to users_url, notice: "User created successfully."
    else
      render 'new'
    end
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])
    @user.first_name = params[:first_name]
    @user.last_name = params[:last_name]
    @user.home_city = params[:home_city]
    @user.home_state = params[:home_state]
    @user.home_country = params[:home_country]
    @user.email = params[:email]
    @user.user_name = params[:user_name]
    @user.password = params[:password]
    @user.photo_url = params[:photo_url]

    if @user.save
      redirect_to users_url, notice: "User updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find_by(id: params[:id])
    @user.destroy

    redirect_to users_url, notice: "User deleted."
  end
end

app/views/users/edit.html.erb
<div class="page-header">
  <h1>Editing User <%= @user.full_name %>'s Profile</h1>
</div>

<%= form_tag(user_url(@user), method: 'patch', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :first_name, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :first_name, @user.first_name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :last_name, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :last_name, @user.last_name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :home_city, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :home_city, @user.home_city, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :home_state, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :home_state, @user.home_state, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :home_country, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :home_country, @user.home_country, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :email, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :email, @user.email, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :user_name, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :user_name, @user.user_name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :password, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= password_field_tag :password, @user.password, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :photo_url, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :photo_url, @user.photo_url, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Update User", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="page-header">
  <h1>Users</h1>
</div>

<p><%= link_to 'Add a New User', new_user_url, class: 'btn btn-primary' %></p>

<table class="table table-hover">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Home city</th>
      <th>Home state</th>
      <th>Home country</th>
      <th>Email</th>
      <th>User name</th>
      <th>Password</th>
      <th>Picture</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.home_city %></td>
        <td><%= user.home_state %></td>
        <td><%= user.home_country %></td>
        <td><%= user.email %></td>
        <td><%= user.user_name %></td>
        <td><%= user.password %></td>
        <td><%= image_tag user.photo_url, width: 40, class: "img-circle" %></td>
        <td><%= link_to '<i class="fa fa-search-plus"></i>'.html_safe, user_url(user), class: 'btn btn-primary' %></td>
        <td><%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_user_url(user), class: 'btn btn-warning' %></td>
        <td><%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, user_url(user), method: 'delete', data: { confirm: "Do you really want to delete this user?" }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<div class="page-header">
  <h1>New User</h1>
</div>

<%= form_tag(users_url, method: 'post', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :first_name, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :first_name, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :last_name, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :last_name, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :home_city, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :home_city, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :home_state, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :home_state, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :home_country, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :home_country, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :email, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :email, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :user_name, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :user_name, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :password, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= password_field_tag :password, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :photo_url, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :photo_url, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Create User", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="page-header">
  <h1><%= image_tag @user.photo_url, width: 70, class: "img-circle" %> <%= @user.full_name %>'s Profile</h1>
</div>

<dl class="dl-horizontal">
  <dt>First name</dt>
  <dd><%= @user.first_name %></dd>

  <dt>Last name</dt>
  <dd><%= @user.last_name %></dd>

  <dt>Home city</dt>
  <dd><%= @user.home_city %></dd>

  <dt>Home state</dt>
  <dd><%= @user.home_state %></dd>

  <dt>Home country</dt>
  <dd><%= @user.home_country %></dd>

  <dt>Email</dt>
  <dd><%= @user.email %></dd>

  <dt>User name</dt>
  <dd><%= @user.user_name %></dd>

  <dt>Password</dt>
  <dd><%= @user.password %></dd>

  <dt>Photo url</dt>
  <dd><%= @user.photo_url %>

</dl>