config/routes.rb
Travel::Application.routes.draw do
  get '/photo_responses/new', controller: 'photo_responses', action: 'new', as: 'new_photo_response'
  post '/photo_responses', controller: 'photo_responses', action: 'create', as: 'photo_responses'

  get '/photo_responses', controller: 'photo_responses', action: 'index'
  get '/photo_responses/:id', controller: 'photo_responses', action: 'show', as: 'photo_response'

  get '/photo_responses/:id/edit', controller: 'photo_responses', action: 'edit', as: 'edit_photo_response'
  patch '/photo_responses/:id', controller: 'photo_responses', action: 'update'

  delete '/photo_responses/:id', controller: 'photo_responses', action: 'destroy'

  root 'requests#index'

  get '/photos/new', controller: 'photos', action: 'new', as: 'new_photo'
  post '/photos', controller: 'photos', action: 'create', as: 'photos'

  get '/photos', controller: 'photos', action: 'index'
  get '/photos/:id', controller: 'photos', action: 'show', as: 'photo'

  get '/photos/:id/edit', controller: 'photos', action: 'edit', as: 'edit_photo'
  patch '/photos/:id', controller: 'photos', action: 'update'

  delete '/photos/:id', controller: 'photos', action: 'destroy'

  get '/replies/new', controller: 'replies', action: 'new', as: 'new_reply'
  post '/replies', controller: 'replies', action: 'create', as: 'replies'

  get '/replies', controller: 'replies', action: 'index'
  get '/replies/:id', controller: 'replies', action: 'show', as: 'reply'

  get '/replies/:id/edit', controller: 'replies', action: 'edit', as: 'edit_reply'
  patch '/replies/:id', controller: 'replies', action: 'update'

  delete '/replies/:id', controller: 'replies', action: 'destroy'

  get '/requests/new', controller: 'requests', action: 'new', as: 'new_request'
  post '/requests', controller: 'requests', action: 'create', as: 'requests'

  get '/requests', controller: 'requests', action: 'index'
  get '/requests/:id', controller: 'requests', action: 'show', as: 'request'

  get '/requests/:id/edit', controller: 'requests', action: 'edit', as: 'edit_request'
  patch '/requests/:id', controller: 'requests', action: 'update'

  delete '/requests/:id', controller: 'requests', action: 'destroy'

  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create', as: 'users'

  get '/users', controller: 'users', action: 'index'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  patch '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

end

app/controllers/photo_responses_controller.rb
class PhotoResponsesController < ApplicationController

  def index
    @photo_responses = PhotoResponse.all
  end

  def show
    @photo_response = PhotoResponse.find_by(id: params[:id])
  end

  def new
  end

  def create
    @photo_response = PhotoResponse.new
    @photo_response.photo_id = params[:photo_id]
    @photo_response.reply_id = params[:reply_id]

    if @photo_response.save
      redirect_to photo_responses_url, notice: "Photo response created successfully."
    else
      render 'new'
    end
  end

  def edit
    @photo_response = PhotoResponse.find_by(id: params[:id])
  end

  def update
    @photo_response = PhotoResponse.find_by(id: params[:id])
    @photo_response.photo_id = params[:photo_id]
    @photo_response.reply_id = params[:reply_id]

    if @photo_response.save
      redirect_to photo_responses_url, notice: "Photo response updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @photo_response = PhotoResponse.find_by(id: params[:id])
    @photo_response.destroy

    redirect_to photo_responses_url, notice: "Photo response deleted."
  end
end

app/views/photo_responses/edit.html.erb
<h1>Editing Photo Response #<%= @photo_response.id %></h1>

<%= form_tag(photo_response_url(@photo_response), method: 'patch') do %>
  <div>
    <%= label_tag :photo_id %><br />
    <%= number_field_tag :photo_id, @photo_response.photo_id %>
  </div>

  <div>
    <%= label_tag :reply_id %><br />
    <%= number_field_tag :reply_id, @photo_response.reply_id %>
  </div>

  <div>
    <%= submit_tag "Update Photo Response" %>
  </div>
<% end %>

app/views/photo_responses/index.html.erb
<h1>Photo responses</h1>

<p><%= link_to 'Add a New Photo Response', new_photo_response_url %></p>

<table>
  <thead>
    <tr>
      <th>Photo</th>
      <th>Reply</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @photo_responses.each do |photo_response| %>
    <tr>
      <td><%= photo_response.photo_id %></td>
      <td><%= photo_response.reply_id %></td>
      <td><%= link_to 'Show', photo_response_url(photo_response) %></td>
      <td><%= link_to 'Edit', edit_photo_response_url(photo_response) %></td>
      <td><%= link_to 'Destroy', photo_response_url(photo_response), method: 'delete', data: { confirm: "Do you really want to delete this photo_response?" } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/photo_responses/new.html.erb
<div class="page-header">
  <h1>New Photo Response</h1>
</div>

<%= form_tag(photo_responses_url, method: 'post', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :photo_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
       <%= select_tag :photo_id, options_from_collection_for_select(Photo.all, :id, :photo_caption), class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :reply_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
       <%= select_tag :reply_id, options_from_collection_for_select(Reply.all, :id, :id), class: 'form-control' %>
    </div>
  </div>

<div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Create Photo Response", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>
  
  

app/views/photo_responses/show.html.erb
<h1>Photo Response #<%= @photo_response.id %></h1>

<dl>
  <dt>Photo</dt>
  <dd><%= @photo_response.photo_id %></dd>

  <dt>Reply</dt>
  <dd><%= @photo_response.reply_id %></dd>

</dl>