config/routes.rb
Travel::Application.routes.draw do
  get '/photo_responses/new', controller: 'photo_responses', action: 'new', as: 'new_photo_response'
  post '/photo_responses', controller: 'photo_responses', action: 'create', as: 'photo_responses'

  get '/photo_responses', controller: 'photo_responses', action: 'index'
  get '/photo_responses/:id', controller: 'photo_responses', action: 'show', as: 'photo_response'

  get '/photo_responses/:id/edit', controller: 'photo_responses', action: 'edit', as: 'edit_photo_response'
  patch '/photo_responses/:id', controller: 'photo_responses', action: 'update'

  delete '/photo_responses/:id', controller: 'photo_responses', action: 'destroy'

  root 'requests#index'

  get '/photos/new', controller: 'photos', action: 'new', as: 'new_photo'
  post '/photos', controller: 'photos', action: 'create', as: 'photos'

  get '/photos', controller: 'photos', action: 'index'
  get '/photos/:id', controller: 'photos', action: 'show', as: 'photo'

  get '/photos/:id/edit', controller: 'photos', action: 'edit', as: 'edit_photo'
  patch '/photos/:id', controller: 'photos', action: 'update'

  delete '/photos/:id', controller: 'photos', action: 'destroy'

  get '/replies/new', controller: 'replies', action: 'new', as: 'new_reply'
  post '/replies', controller: 'replies', action: 'create', as: 'replies'

  get '/replies', controller: 'replies', action: 'index'
  get '/replies/:id', controller: 'replies', action: 'show', as: 'reply'

  get '/replies/:id/edit', controller: 'replies', action: 'edit', as: 'edit_reply'
  patch '/replies/:id', controller: 'replies', action: 'update'

  delete '/replies/:id', controller: 'replies', action: 'destroy'

  get '/requests/new', controller: 'requests', action: 'new', as: 'new_request'
  post '/requests', controller: 'requests', action: 'create', as: 'requests'

  get '/requests', controller: 'requests', action: 'index'
  get '/requests/:id', controller: 'requests', action: 'show', as: 'request'

  get '/requests/:id/edit', controller: 'requests', action: 'edit', as: 'edit_request'
  patch '/requests/:id', controller: 'requests', action: 'update'

  delete '/requests/:id', controller: 'requests', action: 'destroy'

  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create', as: 'users'

  get '/users', controller: 'users', action: 'index'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  patch '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Travel</title>

  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootswatch/3.0.2/flatly/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.2/css/font-awesome.min.css">

  <style>
    /* Only necessary if you are using navbar-fixed-top */
    body {
      padding-top: 50px;
    }
  </style>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to Rails.application.class.parent_name, root_url, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
       
        <li><%= link_to "Profile", users_url %></li>
        <li><%= link_to "Requests", requests_url %></li>
        <li><%= link_to "Replies", replies_url %></li>
       </ul>
    </div><!-- /.navbar-collapse -->
  </nav>

  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>